# Netlify configuration file
[build]
  publish = "."

# Redirect all paths to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to improve security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    # Cache settings
    Cache-Control = "public, max-age=31536000"

# Cache settings for images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"